name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    if: always()

    strategy:
      max-parallel: 1
      matrix:
        include:
          - python-version: "3.6.15"
          - python-version: "3.7.17"
          - python-version: "3.8.18"
          - python-version: "3.9.18"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Install test requirements
        run: python -m pip install -U pytest pytest-cov coveralls

      - name: Run tests
        run: python -m pytest tests.py --cov=gspreaddict
        env:
          SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}

      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    if: always()
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
